name: Main
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".github/dependabot.yml"
env:
  CARGO_TERM_COLOR: always
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v2

      - name: Install riscv32i-unknown-none-elf target
        run: rustup target add riscv32i-unknown-none-elf

      - name: Install LiteX
        run: |
          mkdir litex
          cd litex
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          chmod +x litex_setup.py
          ./litex_setup.py --init --install --user

      - name: Clippy
        run: cargo clippy --no-deps --examples --all-features -- -D warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Cache crates
        uses: Swatinem/rust-cache@v2

      - name: Install Taplo
        run: cargo install taplo-cli

      - name: Format
        run: |
          cargo fmt --check
          taplo fmt --check
